import type { Metadata } from "next";
import { Toaster } from "@/components/ui/sonner";
import { Providers } from "./providers";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>{children}</Providers>
        <Toaster
          position="bottom-left"
          toastOptions={{
            classNames: {
              toast:
                "p-4 rounded-xl text-base shadow-lg border border-slate-700 bg-slate-900 text-white",
              title: "text-lg font-semibold",
              description: "text-sm text-slate-300",
              actionButton: "bg-slate-700 text-white px-3 py-1 rounded-lg",
            },
          }}
        />
      </body>
    </html>
  );
}
